package cn.uc.yiqibang.dao;

import cn.uc.yiqibang.bean.Areas;

public interface AreasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areas
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areas
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    int insert(Areas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areas
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    int insertSelective(Areas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areas
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    Areas selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areas
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    int updateByPrimaryKeySelective(Areas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areas
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    int updateByPrimaryKey(Areas record);
}