package cn.uc.yiqibang.dao;

import cn.uc.yiqibang.bean.Cities;
import cn.uc.yiqibang.bean.CitiesExample;
import java.util.List;

public interface CitiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    int insert(Cities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    int insertSelective(Cities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    List<Cities> selectByExample(CitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    Cities selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    int updateByPrimaryKeySelective(Cities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    int updateByPrimaryKey(Cities record);
}