package cn.uc.yiqibang.dao;

import cn.uc.yiqibang.bean.Provinces;
import cn.uc.yiqibang.bean.ProvincesExample;
import java.util.List;

public interface ProvincesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    int insert(Provinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    int insertSelective(Provinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    List<Provinces> selectByExample(ProvincesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    Provinces selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    int updateByPrimaryKeySelective(Provinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    int updateByPrimaryKey(Provinces record);
}