package cn.uc.yiqibang.bean;

import java.util.ArrayList;
import java.util.List;

public class TAdminExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_admin
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_admin
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_admin
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public TAdminExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_admin
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTUIdIsNull() {
            addCriterion("t_u_id is null");
            return (Criteria) this;
        }

        public Criteria andTUIdIsNotNull() {
            addCriterion("t_u_id is not null");
            return (Criteria) this;
        }

        public Criteria andTUIdEqualTo(Integer value) {
            addCriterion("t_u_id =", value, "tUId");
            return (Criteria) this;
        }

        public Criteria andTUIdNotEqualTo(Integer value) {
            addCriterion("t_u_id <>", value, "tUId");
            return (Criteria) this;
        }

        public Criteria andTUIdGreaterThan(Integer value) {
            addCriterion("t_u_id >", value, "tUId");
            return (Criteria) this;
        }

        public Criteria andTUIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("t_u_id >=", value, "tUId");
            return (Criteria) this;
        }

        public Criteria andTUIdLessThan(Integer value) {
            addCriterion("t_u_id <", value, "tUId");
            return (Criteria) this;
        }

        public Criteria andTUIdLessThanOrEqualTo(Integer value) {
            addCriterion("t_u_id <=", value, "tUId");
            return (Criteria) this;
        }

        public Criteria andTUIdIn(List<Integer> values) {
            addCriterion("t_u_id in", values, "tUId");
            return (Criteria) this;
        }

        public Criteria andTUIdNotIn(List<Integer> values) {
            addCriterion("t_u_id not in", values, "tUId");
            return (Criteria) this;
        }

        public Criteria andTUIdBetween(Integer value1, Integer value2) {
            addCriterion("t_u_id between", value1, value2, "tUId");
            return (Criteria) this;
        }

        public Criteria andTUIdNotBetween(Integer value1, Integer value2) {
            addCriterion("t_u_id not between", value1, value2, "tUId");
            return (Criteria) this;
        }

        public Criteria andUStateIsNull() {
            addCriterion("u_state is null");
            return (Criteria) this;
        }

        public Criteria andUStateIsNotNull() {
            addCriterion("u_state is not null");
            return (Criteria) this;
        }

        public Criteria andUStateEqualTo(Boolean value) {
            addCriterion("u_state =", value, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateNotEqualTo(Boolean value) {
            addCriterion("u_state <>", value, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateGreaterThan(Boolean value) {
            addCriterion("u_state >", value, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("u_state >=", value, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateLessThan(Boolean value) {
            addCriterion("u_state <", value, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateLessThanOrEqualTo(Boolean value) {
            addCriterion("u_state <=", value, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateIn(List<Boolean> values) {
            addCriterion("u_state in", values, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateNotIn(List<Boolean> values) {
            addCriterion("u_state not in", values, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateBetween(Boolean value1, Boolean value2) {
            addCriterion("u_state between", value1, value2, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("u_state not between", value1, value2, "uState");
            return (Criteria) this;
        }

        public Criteria andULevelIsNull() {
            addCriterion("u_level is null");
            return (Criteria) this;
        }

        public Criteria andULevelIsNotNull() {
            addCriterion("u_level is not null");
            return (Criteria) this;
        }

        public Criteria andULevelEqualTo(Integer value) {
            addCriterion("u_level =", value, "uLevel");
            return (Criteria) this;
        }

        public Criteria andULevelNotEqualTo(Integer value) {
            addCriterion("u_level <>", value, "uLevel");
            return (Criteria) this;
        }

        public Criteria andULevelGreaterThan(Integer value) {
            addCriterion("u_level >", value, "uLevel");
            return (Criteria) this;
        }

        public Criteria andULevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("u_level >=", value, "uLevel");
            return (Criteria) this;
        }

        public Criteria andULevelLessThan(Integer value) {
            addCriterion("u_level <", value, "uLevel");
            return (Criteria) this;
        }

        public Criteria andULevelLessThanOrEqualTo(Integer value) {
            addCriterion("u_level <=", value, "uLevel");
            return (Criteria) this;
        }

        public Criteria andULevelIn(List<Integer> values) {
            addCriterion("u_level in", values, "uLevel");
            return (Criteria) this;
        }

        public Criteria andULevelNotIn(List<Integer> values) {
            addCriterion("u_level not in", values, "uLevel");
            return (Criteria) this;
        }

        public Criteria andULevelBetween(Integer value1, Integer value2) {
            addCriterion("u_level between", value1, value2, "uLevel");
            return (Criteria) this;
        }

        public Criteria andULevelNotBetween(Integer value1, Integer value2) {
            addCriterion("u_level not between", value1, value2, "uLevel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_admin
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 13 14:55:36 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_admin
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}