package cn.uc.yiqibang.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TNewsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_news
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_news
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_news
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public TNewsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_news
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTTIdIsNull() {
            addCriterion("t_t_id is null");
            return (Criteria) this;
        }

        public Criteria andTTIdIsNotNull() {
            addCriterion("t_t_id is not null");
            return (Criteria) this;
        }

        public Criteria andTTIdEqualTo(Integer value) {
            addCriterion("t_t_id =", value, "tTId");
            return (Criteria) this;
        }

        public Criteria andTTIdNotEqualTo(Integer value) {
            addCriterion("t_t_id <>", value, "tTId");
            return (Criteria) this;
        }

        public Criteria andTTIdGreaterThan(Integer value) {
            addCriterion("t_t_id >", value, "tTId");
            return (Criteria) this;
        }

        public Criteria andTTIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("t_t_id >=", value, "tTId");
            return (Criteria) this;
        }

        public Criteria andTTIdLessThan(Integer value) {
            addCriterion("t_t_id <", value, "tTId");
            return (Criteria) this;
        }

        public Criteria andTTIdLessThanOrEqualTo(Integer value) {
            addCriterion("t_t_id <=", value, "tTId");
            return (Criteria) this;
        }

        public Criteria andTTIdIn(List<Integer> values) {
            addCriterion("t_t_id in", values, "tTId");
            return (Criteria) this;
        }

        public Criteria andTTIdNotIn(List<Integer> values) {
            addCriterion("t_t_id not in", values, "tTId");
            return (Criteria) this;
        }

        public Criteria andTTIdBetween(Integer value1, Integer value2) {
            addCriterion("t_t_id between", value1, value2, "tTId");
            return (Criteria) this;
        }

        public Criteria andTTIdNotBetween(Integer value1, Integer value2) {
            addCriterion("t_t_id not between", value1, value2, "tTId");
            return (Criteria) this;
        }

        public Criteria andNTitleIsNull() {
            addCriterion("n_title is null");
            return (Criteria) this;
        }

        public Criteria andNTitleIsNotNull() {
            addCriterion("n_title is not null");
            return (Criteria) this;
        }

        public Criteria andNTitleEqualTo(String value) {
            addCriterion("n_title =", value, "nTitle");
            return (Criteria) this;
        }

        public Criteria andNTitleNotEqualTo(String value) {
            addCriterion("n_title <>", value, "nTitle");
            return (Criteria) this;
        }

        public Criteria andNTitleGreaterThan(String value) {
            addCriterion("n_title >", value, "nTitle");
            return (Criteria) this;
        }

        public Criteria andNTitleGreaterThanOrEqualTo(String value) {
            addCriterion("n_title >=", value, "nTitle");
            return (Criteria) this;
        }

        public Criteria andNTitleLessThan(String value) {
            addCriterion("n_title <", value, "nTitle");
            return (Criteria) this;
        }

        public Criteria andNTitleLessThanOrEqualTo(String value) {
            addCriterion("n_title <=", value, "nTitle");
            return (Criteria) this;
        }

        public Criteria andNTitleLike(String value) {
            addCriterion("n_title like", value, "nTitle");
            return (Criteria) this;
        }

        public Criteria andNTitleNotLike(String value) {
            addCriterion("n_title not like", value, "nTitle");
            return (Criteria) this;
        }

        public Criteria andNTitleIn(List<String> values) {
            addCriterion("n_title in", values, "nTitle");
            return (Criteria) this;
        }

        public Criteria andNTitleNotIn(List<String> values) {
            addCriterion("n_title not in", values, "nTitle");
            return (Criteria) this;
        }

        public Criteria andNTitleBetween(String value1, String value2) {
            addCriterion("n_title between", value1, value2, "nTitle");
            return (Criteria) this;
        }

        public Criteria andNTitleNotBetween(String value1, String value2) {
            addCriterion("n_title not between", value1, value2, "nTitle");
            return (Criteria) this;
        }

        public Criteria andNSourceIsNull() {
            addCriterion("n_source is null");
            return (Criteria) this;
        }

        public Criteria andNSourceIsNotNull() {
            addCriterion("n_source is not null");
            return (Criteria) this;
        }

        public Criteria andNSourceEqualTo(String value) {
            addCriterion("n_source =", value, "nSource");
            return (Criteria) this;
        }

        public Criteria andNSourceNotEqualTo(String value) {
            addCriterion("n_source <>", value, "nSource");
            return (Criteria) this;
        }

        public Criteria andNSourceGreaterThan(String value) {
            addCriterion("n_source >", value, "nSource");
            return (Criteria) this;
        }

        public Criteria andNSourceGreaterThanOrEqualTo(String value) {
            addCriterion("n_source >=", value, "nSource");
            return (Criteria) this;
        }

        public Criteria andNSourceLessThan(String value) {
            addCriterion("n_source <", value, "nSource");
            return (Criteria) this;
        }

        public Criteria andNSourceLessThanOrEqualTo(String value) {
            addCriterion("n_source <=", value, "nSource");
            return (Criteria) this;
        }

        public Criteria andNSourceLike(String value) {
            addCriterion("n_source like", value, "nSource");
            return (Criteria) this;
        }

        public Criteria andNSourceNotLike(String value) {
            addCriterion("n_source not like", value, "nSource");
            return (Criteria) this;
        }

        public Criteria andNSourceIn(List<String> values) {
            addCriterion("n_source in", values, "nSource");
            return (Criteria) this;
        }

        public Criteria andNSourceNotIn(List<String> values) {
            addCriterion("n_source not in", values, "nSource");
            return (Criteria) this;
        }

        public Criteria andNSourceBetween(String value1, String value2) {
            addCriterion("n_source between", value1, value2, "nSource");
            return (Criteria) this;
        }

        public Criteria andNSourceNotBetween(String value1, String value2) {
            addCriterion("n_source not between", value1, value2, "nSource");
            return (Criteria) this;
        }

        public Criteria andNCreatetimeIsNull() {
            addCriterion("n_createtime is null");
            return (Criteria) this;
        }

        public Criteria andNCreatetimeIsNotNull() {
            addCriterion("n_createtime is not null");
            return (Criteria) this;
        }

        public Criteria andNCreatetimeEqualTo(Date value) {
            addCriterion("n_createtime =", value, "nCreatetime");
            return (Criteria) this;
        }

        public Criteria andNCreatetimeNotEqualTo(Date value) {
            addCriterion("n_createtime <>", value, "nCreatetime");
            return (Criteria) this;
        }

        public Criteria andNCreatetimeGreaterThan(Date value) {
            addCriterion("n_createtime >", value, "nCreatetime");
            return (Criteria) this;
        }

        public Criteria andNCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("n_createtime >=", value, "nCreatetime");
            return (Criteria) this;
        }

        public Criteria andNCreatetimeLessThan(Date value) {
            addCriterion("n_createtime <", value, "nCreatetime");
            return (Criteria) this;
        }

        public Criteria andNCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("n_createtime <=", value, "nCreatetime");
            return (Criteria) this;
        }

        public Criteria andNCreatetimeIn(List<Date> values) {
            addCriterion("n_createtime in", values, "nCreatetime");
            return (Criteria) this;
        }

        public Criteria andNCreatetimeNotIn(List<Date> values) {
            addCriterion("n_createtime not in", values, "nCreatetime");
            return (Criteria) this;
        }

        public Criteria andNCreatetimeBetween(Date value1, Date value2) {
            addCriterion("n_createtime between", value1, value2, "nCreatetime");
            return (Criteria) this;
        }

        public Criteria andNCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("n_createtime not between", value1, value2, "nCreatetime");
            return (Criteria) this;
        }

        public Criteria andNCommcountIsNull() {
            addCriterion("n_commcount is null");
            return (Criteria) this;
        }

        public Criteria andNCommcountIsNotNull() {
            addCriterion("n_commcount is not null");
            return (Criteria) this;
        }

        public Criteria andNCommcountEqualTo(Integer value) {
            addCriterion("n_commcount =", value, "nCommcount");
            return (Criteria) this;
        }

        public Criteria andNCommcountNotEqualTo(Integer value) {
            addCriterion("n_commcount <>", value, "nCommcount");
            return (Criteria) this;
        }

        public Criteria andNCommcountGreaterThan(Integer value) {
            addCriterion("n_commcount >", value, "nCommcount");
            return (Criteria) this;
        }

        public Criteria andNCommcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_commcount >=", value, "nCommcount");
            return (Criteria) this;
        }

        public Criteria andNCommcountLessThan(Integer value) {
            addCriterion("n_commcount <", value, "nCommcount");
            return (Criteria) this;
        }

        public Criteria andNCommcountLessThanOrEqualTo(Integer value) {
            addCriterion("n_commcount <=", value, "nCommcount");
            return (Criteria) this;
        }

        public Criteria andNCommcountIn(List<Integer> values) {
            addCriterion("n_commcount in", values, "nCommcount");
            return (Criteria) this;
        }

        public Criteria andNCommcountNotIn(List<Integer> values) {
            addCriterion("n_commcount not in", values, "nCommcount");
            return (Criteria) this;
        }

        public Criteria andNCommcountBetween(Integer value1, Integer value2) {
            addCriterion("n_commcount between", value1, value2, "nCommcount");
            return (Criteria) this;
        }

        public Criteria andNCommcountNotBetween(Integer value1, Integer value2) {
            addCriterion("n_commcount not between", value1, value2, "nCommcount");
            return (Criteria) this;
        }

        public Criteria andNReadcountIsNull() {
            addCriterion("n_readcount is null");
            return (Criteria) this;
        }

        public Criteria andNReadcountIsNotNull() {
            addCriterion("n_readcount is not null");
            return (Criteria) this;
        }

        public Criteria andNReadcountEqualTo(Integer value) {
            addCriterion("n_readcount =", value, "nReadcount");
            return (Criteria) this;
        }

        public Criteria andNReadcountNotEqualTo(Integer value) {
            addCriterion("n_readcount <>", value, "nReadcount");
            return (Criteria) this;
        }

        public Criteria andNReadcountGreaterThan(Integer value) {
            addCriterion("n_readcount >", value, "nReadcount");
            return (Criteria) this;
        }

        public Criteria andNReadcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_readcount >=", value, "nReadcount");
            return (Criteria) this;
        }

        public Criteria andNReadcountLessThan(Integer value) {
            addCriterion("n_readcount <", value, "nReadcount");
            return (Criteria) this;
        }

        public Criteria andNReadcountLessThanOrEqualTo(Integer value) {
            addCriterion("n_readcount <=", value, "nReadcount");
            return (Criteria) this;
        }

        public Criteria andNReadcountIn(List<Integer> values) {
            addCriterion("n_readcount in", values, "nReadcount");
            return (Criteria) this;
        }

        public Criteria andNReadcountNotIn(List<Integer> values) {
            addCriterion("n_readcount not in", values, "nReadcount");
            return (Criteria) this;
        }

        public Criteria andNReadcountBetween(Integer value1, Integer value2) {
            addCriterion("n_readcount between", value1, value2, "nReadcount");
            return (Criteria) this;
        }

        public Criteria andNReadcountNotBetween(Integer value1, Integer value2) {
            addCriterion("n_readcount not between", value1, value2, "nReadcount");
            return (Criteria) this;
        }

        public Criteria andNAuthorIsNull() {
            addCriterion("n_author is null");
            return (Criteria) this;
        }

        public Criteria andNAuthorIsNotNull() {
            addCriterion("n_author is not null");
            return (Criteria) this;
        }

        public Criteria andNAuthorEqualTo(String value) {
            addCriterion("n_author =", value, "nAuthor");
            return (Criteria) this;
        }

        public Criteria andNAuthorNotEqualTo(String value) {
            addCriterion("n_author <>", value, "nAuthor");
            return (Criteria) this;
        }

        public Criteria andNAuthorGreaterThan(String value) {
            addCriterion("n_author >", value, "nAuthor");
            return (Criteria) this;
        }

        public Criteria andNAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("n_author >=", value, "nAuthor");
            return (Criteria) this;
        }

        public Criteria andNAuthorLessThan(String value) {
            addCriterion("n_author <", value, "nAuthor");
            return (Criteria) this;
        }

        public Criteria andNAuthorLessThanOrEqualTo(String value) {
            addCriterion("n_author <=", value, "nAuthor");
            return (Criteria) this;
        }

        public Criteria andNAuthorLike(String value) {
            addCriterion("n_author like", value, "nAuthor");
            return (Criteria) this;
        }

        public Criteria andNAuthorNotLike(String value) {
            addCriterion("n_author not like", value, "nAuthor");
            return (Criteria) this;
        }

        public Criteria andNAuthorIn(List<String> values) {
            addCriterion("n_author in", values, "nAuthor");
            return (Criteria) this;
        }

        public Criteria andNAuthorNotIn(List<String> values) {
            addCriterion("n_author not in", values, "nAuthor");
            return (Criteria) this;
        }

        public Criteria andNAuthorBetween(String value1, String value2) {
            addCriterion("n_author between", value1, value2, "nAuthor");
            return (Criteria) this;
        }

        public Criteria andNAuthorNotBetween(String value1, String value2) {
            addCriterion("n_author not between", value1, value2, "nAuthor");
            return (Criteria) this;
        }

        public Criteria andNSharecountIsNull() {
            addCriterion("n_sharecount is null");
            return (Criteria) this;
        }

        public Criteria andNSharecountIsNotNull() {
            addCriterion("n_sharecount is not null");
            return (Criteria) this;
        }

        public Criteria andNSharecountEqualTo(Integer value) {
            addCriterion("n_sharecount =", value, "nSharecount");
            return (Criteria) this;
        }

        public Criteria andNSharecountNotEqualTo(Integer value) {
            addCriterion("n_sharecount <>", value, "nSharecount");
            return (Criteria) this;
        }

        public Criteria andNSharecountGreaterThan(Integer value) {
            addCriterion("n_sharecount >", value, "nSharecount");
            return (Criteria) this;
        }

        public Criteria andNSharecountGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_sharecount >=", value, "nSharecount");
            return (Criteria) this;
        }

        public Criteria andNSharecountLessThan(Integer value) {
            addCriterion("n_sharecount <", value, "nSharecount");
            return (Criteria) this;
        }

        public Criteria andNSharecountLessThanOrEqualTo(Integer value) {
            addCriterion("n_sharecount <=", value, "nSharecount");
            return (Criteria) this;
        }

        public Criteria andNSharecountIn(List<Integer> values) {
            addCriterion("n_sharecount in", values, "nSharecount");
            return (Criteria) this;
        }

        public Criteria andNSharecountNotIn(List<Integer> values) {
            addCriterion("n_sharecount not in", values, "nSharecount");
            return (Criteria) this;
        }

        public Criteria andNSharecountBetween(Integer value1, Integer value2) {
            addCriterion("n_sharecount between", value1, value2, "nSharecount");
            return (Criteria) this;
        }

        public Criteria andNSharecountNotBetween(Integer value1, Integer value2) {
            addCriterion("n_sharecount not between", value1, value2, "nSharecount");
            return (Criteria) this;
        }

        public Criteria andNIfhotIsNull() {
            addCriterion("n_ifhot is null");
            return (Criteria) this;
        }

        public Criteria andNIfhotIsNotNull() {
            addCriterion("n_ifhot is not null");
            return (Criteria) this;
        }

        public Criteria andNIfhotEqualTo(Boolean value) {
            addCriterion("n_ifhot =", value, "nIfhot");
            return (Criteria) this;
        }

        public Criteria andNIfhotNotEqualTo(Boolean value) {
            addCriterion("n_ifhot <>", value, "nIfhot");
            return (Criteria) this;
        }

        public Criteria andNIfhotGreaterThan(Boolean value) {
            addCriterion("n_ifhot >", value, "nIfhot");
            return (Criteria) this;
        }

        public Criteria andNIfhotGreaterThanOrEqualTo(Boolean value) {
            addCriterion("n_ifhot >=", value, "nIfhot");
            return (Criteria) this;
        }

        public Criteria andNIfhotLessThan(Boolean value) {
            addCriterion("n_ifhot <", value, "nIfhot");
            return (Criteria) this;
        }

        public Criteria andNIfhotLessThanOrEqualTo(Boolean value) {
            addCriterion("n_ifhot <=", value, "nIfhot");
            return (Criteria) this;
        }

        public Criteria andNIfhotIn(List<Boolean> values) {
            addCriterion("n_ifhot in", values, "nIfhot");
            return (Criteria) this;
        }

        public Criteria andNIfhotNotIn(List<Boolean> values) {
            addCriterion("n_ifhot not in", values, "nIfhot");
            return (Criteria) this;
        }

        public Criteria andNIfhotBetween(Boolean value1, Boolean value2) {
            addCriterion("n_ifhot between", value1, value2, "nIfhot");
            return (Criteria) this;
        }

        public Criteria andNIfhotNotBetween(Boolean value1, Boolean value2) {
            addCriterion("n_ifhot not between", value1, value2, "nIfhot");
            return (Criteria) this;
        }

        public Criteria andNIfreportIsNull() {
            addCriterion("n_ifreport is null");
            return (Criteria) this;
        }

        public Criteria andNIfreportIsNotNull() {
            addCriterion("n_ifreport is not null");
            return (Criteria) this;
        }

        public Criteria andNIfreportEqualTo(Boolean value) {
            addCriterion("n_ifreport =", value, "nIfreport");
            return (Criteria) this;
        }

        public Criteria andNIfreportNotEqualTo(Boolean value) {
            addCriterion("n_ifreport <>", value, "nIfreport");
            return (Criteria) this;
        }

        public Criteria andNIfreportGreaterThan(Boolean value) {
            addCriterion("n_ifreport >", value, "nIfreport");
            return (Criteria) this;
        }

        public Criteria andNIfreportGreaterThanOrEqualTo(Boolean value) {
            addCriterion("n_ifreport >=", value, "nIfreport");
            return (Criteria) this;
        }

        public Criteria andNIfreportLessThan(Boolean value) {
            addCriterion("n_ifreport <", value, "nIfreport");
            return (Criteria) this;
        }

        public Criteria andNIfreportLessThanOrEqualTo(Boolean value) {
            addCriterion("n_ifreport <=", value, "nIfreport");
            return (Criteria) this;
        }

        public Criteria andNIfreportIn(List<Boolean> values) {
            addCriterion("n_ifreport in", values, "nIfreport");
            return (Criteria) this;
        }

        public Criteria andNIfreportNotIn(List<Boolean> values) {
            addCriterion("n_ifreport not in", values, "nIfreport");
            return (Criteria) this;
        }

        public Criteria andNIfreportBetween(Boolean value1, Boolean value2) {
            addCriterion("n_ifreport between", value1, value2, "nIfreport");
            return (Criteria) this;
        }

        public Criteria andNIfreportNotBetween(Boolean value1, Boolean value2) {
            addCriterion("n_ifreport not between", value1, value2, "nIfreport");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_news
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 13 14:55:36 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_news
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}