package cn.uc.yiqibang.bean;

import java.util.ArrayList;
import java.util.List;

public class TPicExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pic
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pic
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pic
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public TPicExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pic
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTNIdIsNull() {
            addCriterion("t_n_id is null");
            return (Criteria) this;
        }

        public Criteria andTNIdIsNotNull() {
            addCriterion("t_n_id is not null");
            return (Criteria) this;
        }

        public Criteria andTNIdEqualTo(Integer value) {
            addCriterion("t_n_id =", value, "tNId");
            return (Criteria) this;
        }

        public Criteria andTNIdNotEqualTo(Integer value) {
            addCriterion("t_n_id <>", value, "tNId");
            return (Criteria) this;
        }

        public Criteria andTNIdGreaterThan(Integer value) {
            addCriterion("t_n_id >", value, "tNId");
            return (Criteria) this;
        }

        public Criteria andTNIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("t_n_id >=", value, "tNId");
            return (Criteria) this;
        }

        public Criteria andTNIdLessThan(Integer value) {
            addCriterion("t_n_id <", value, "tNId");
            return (Criteria) this;
        }

        public Criteria andTNIdLessThanOrEqualTo(Integer value) {
            addCriterion("t_n_id <=", value, "tNId");
            return (Criteria) this;
        }

        public Criteria andTNIdIn(List<Integer> values) {
            addCriterion("t_n_id in", values, "tNId");
            return (Criteria) this;
        }

        public Criteria andTNIdNotIn(List<Integer> values) {
            addCriterion("t_n_id not in", values, "tNId");
            return (Criteria) this;
        }

        public Criteria andTNIdBetween(Integer value1, Integer value2) {
            addCriterion("t_n_id between", value1, value2, "tNId");
            return (Criteria) this;
        }

        public Criteria andTNIdNotBetween(Integer value1, Integer value2) {
            addCriterion("t_n_id not between", value1, value2, "tNId");
            return (Criteria) this;
        }

        public Criteria andPPathIsNull() {
            addCriterion("p_path is null");
            return (Criteria) this;
        }

        public Criteria andPPathIsNotNull() {
            addCriterion("p_path is not null");
            return (Criteria) this;
        }

        public Criteria andPPathEqualTo(String value) {
            addCriterion("p_path =", value, "pPath");
            return (Criteria) this;
        }

        public Criteria andPPathNotEqualTo(String value) {
            addCriterion("p_path <>", value, "pPath");
            return (Criteria) this;
        }

        public Criteria andPPathGreaterThan(String value) {
            addCriterion("p_path >", value, "pPath");
            return (Criteria) this;
        }

        public Criteria andPPathGreaterThanOrEqualTo(String value) {
            addCriterion("p_path >=", value, "pPath");
            return (Criteria) this;
        }

        public Criteria andPPathLessThan(String value) {
            addCriterion("p_path <", value, "pPath");
            return (Criteria) this;
        }

        public Criteria andPPathLessThanOrEqualTo(String value) {
            addCriterion("p_path <=", value, "pPath");
            return (Criteria) this;
        }

        public Criteria andPPathLike(String value) {
            addCriterion("p_path like", value, "pPath");
            return (Criteria) this;
        }

        public Criteria andPPathNotLike(String value) {
            addCriterion("p_path not like", value, "pPath");
            return (Criteria) this;
        }

        public Criteria andPPathIn(List<String> values) {
            addCriterion("p_path in", values, "pPath");
            return (Criteria) this;
        }

        public Criteria andPPathNotIn(List<String> values) {
            addCriterion("p_path not in", values, "pPath");
            return (Criteria) this;
        }

        public Criteria andPPathBetween(String value1, String value2) {
            addCriterion("p_path between", value1, value2, "pPath");
            return (Criteria) this;
        }

        public Criteria andPPathNotBetween(String value1, String value2) {
            addCriterion("p_path not between", value1, value2, "pPath");
            return (Criteria) this;
        }

        public Criteria andPInfoIsNull() {
            addCriterion("p_info is null");
            return (Criteria) this;
        }

        public Criteria andPInfoIsNotNull() {
            addCriterion("p_info is not null");
            return (Criteria) this;
        }

        public Criteria andPInfoEqualTo(String value) {
            addCriterion("p_info =", value, "pInfo");
            return (Criteria) this;
        }

        public Criteria andPInfoNotEqualTo(String value) {
            addCriterion("p_info <>", value, "pInfo");
            return (Criteria) this;
        }

        public Criteria andPInfoGreaterThan(String value) {
            addCriterion("p_info >", value, "pInfo");
            return (Criteria) this;
        }

        public Criteria andPInfoGreaterThanOrEqualTo(String value) {
            addCriterion("p_info >=", value, "pInfo");
            return (Criteria) this;
        }

        public Criteria andPInfoLessThan(String value) {
            addCriterion("p_info <", value, "pInfo");
            return (Criteria) this;
        }

        public Criteria andPInfoLessThanOrEqualTo(String value) {
            addCriterion("p_info <=", value, "pInfo");
            return (Criteria) this;
        }

        public Criteria andPInfoLike(String value) {
            addCriterion("p_info like", value, "pInfo");
            return (Criteria) this;
        }

        public Criteria andPInfoNotLike(String value) {
            addCriterion("p_info not like", value, "pInfo");
            return (Criteria) this;
        }

        public Criteria andPInfoIn(List<String> values) {
            addCriterion("p_info in", values, "pInfo");
            return (Criteria) this;
        }

        public Criteria andPInfoNotIn(List<String> values) {
            addCriterion("p_info not in", values, "pInfo");
            return (Criteria) this;
        }

        public Criteria andPInfoBetween(String value1, String value2) {
            addCriterion("p_info between", value1, value2, "pInfo");
            return (Criteria) this;
        }

        public Criteria andPInfoNotBetween(String value1, String value2) {
            addCriterion("p_info not between", value1, value2, "pInfo");
            return (Criteria) this;
        }

        public Criteria andPAuthorIsNull() {
            addCriterion("p_author is null");
            return (Criteria) this;
        }

        public Criteria andPAuthorIsNotNull() {
            addCriterion("p_author is not null");
            return (Criteria) this;
        }

        public Criteria andPAuthorEqualTo(String value) {
            addCriterion("p_author =", value, "pAuthor");
            return (Criteria) this;
        }

        public Criteria andPAuthorNotEqualTo(String value) {
            addCriterion("p_author <>", value, "pAuthor");
            return (Criteria) this;
        }

        public Criteria andPAuthorGreaterThan(String value) {
            addCriterion("p_author >", value, "pAuthor");
            return (Criteria) this;
        }

        public Criteria andPAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("p_author >=", value, "pAuthor");
            return (Criteria) this;
        }

        public Criteria andPAuthorLessThan(String value) {
            addCriterion("p_author <", value, "pAuthor");
            return (Criteria) this;
        }

        public Criteria andPAuthorLessThanOrEqualTo(String value) {
            addCriterion("p_author <=", value, "pAuthor");
            return (Criteria) this;
        }

        public Criteria andPAuthorLike(String value) {
            addCriterion("p_author like", value, "pAuthor");
            return (Criteria) this;
        }

        public Criteria andPAuthorNotLike(String value) {
            addCriterion("p_author not like", value, "pAuthor");
            return (Criteria) this;
        }

        public Criteria andPAuthorIn(List<String> values) {
            addCriterion("p_author in", values, "pAuthor");
            return (Criteria) this;
        }

        public Criteria andPAuthorNotIn(List<String> values) {
            addCriterion("p_author not in", values, "pAuthor");
            return (Criteria) this;
        }

        public Criteria andPAuthorBetween(String value1, String value2) {
            addCriterion("p_author between", value1, value2, "pAuthor");
            return (Criteria) this;
        }

        public Criteria andPAuthorNotBetween(String value1, String value2) {
            addCriterion("p_author not between", value1, value2, "pAuthor");
            return (Criteria) this;
        }

        public Criteria andPSourceIsNull() {
            addCriterion("p_source is null");
            return (Criteria) this;
        }

        public Criteria andPSourceIsNotNull() {
            addCriterion("p_source is not null");
            return (Criteria) this;
        }

        public Criteria andPSourceEqualTo(String value) {
            addCriterion("p_source =", value, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceNotEqualTo(String value) {
            addCriterion("p_source <>", value, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceGreaterThan(String value) {
            addCriterion("p_source >", value, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceGreaterThanOrEqualTo(String value) {
            addCriterion("p_source >=", value, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceLessThan(String value) {
            addCriterion("p_source <", value, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceLessThanOrEqualTo(String value) {
            addCriterion("p_source <=", value, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceLike(String value) {
            addCriterion("p_source like", value, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceNotLike(String value) {
            addCriterion("p_source not like", value, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceIn(List<String> values) {
            addCriterion("p_source in", values, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceNotIn(List<String> values) {
            addCriterion("p_source not in", values, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceBetween(String value1, String value2) {
            addCriterion("p_source between", value1, value2, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceNotBetween(String value1, String value2) {
            addCriterion("p_source not between", value1, value2, "pSource");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pic
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 13 14:55:36 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pic
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}