package cn.uc.yiqibang.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public TUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUUsernameIsNull() {
            addCriterion("u_username is null");
            return (Criteria) this;
        }

        public Criteria andUUsernameIsNotNull() {
            addCriterion("u_username is not null");
            return (Criteria) this;
        }

        public Criteria andUUsernameEqualTo(String value) {
            addCriterion("u_username =", value, "uUsername");
            return (Criteria) this;
        }

        public Criteria andUUsernameNotEqualTo(String value) {
            addCriterion("u_username <>", value, "uUsername");
            return (Criteria) this;
        }

        public Criteria andUUsernameGreaterThan(String value) {
            addCriterion("u_username >", value, "uUsername");
            return (Criteria) this;
        }

        public Criteria andUUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("u_username >=", value, "uUsername");
            return (Criteria) this;
        }

        public Criteria andUUsernameLessThan(String value) {
            addCriterion("u_username <", value, "uUsername");
            return (Criteria) this;
        }

        public Criteria andUUsernameLessThanOrEqualTo(String value) {
            addCriterion("u_username <=", value, "uUsername");
            return (Criteria) this;
        }

        public Criteria andUUsernameLike(String value) {
            addCriterion("u_username like", value, "uUsername");
            return (Criteria) this;
        }

        public Criteria andUUsernameNotLike(String value) {
            addCriterion("u_username not like", value, "uUsername");
            return (Criteria) this;
        }

        public Criteria andUUsernameIn(List<String> values) {
            addCriterion("u_username in", values, "uUsername");
            return (Criteria) this;
        }

        public Criteria andUUsernameNotIn(List<String> values) {
            addCriterion("u_username not in", values, "uUsername");
            return (Criteria) this;
        }

        public Criteria andUUsernameBetween(String value1, String value2) {
            addCriterion("u_username between", value1, value2, "uUsername");
            return (Criteria) this;
        }

        public Criteria andUUsernameNotBetween(String value1, String value2) {
            addCriterion("u_username not between", value1, value2, "uUsername");
            return (Criteria) this;
        }

        public Criteria andUNicknameIsNull() {
            addCriterion("u_nickname is null");
            return (Criteria) this;
        }

        public Criteria andUNicknameIsNotNull() {
            addCriterion("u_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andUNicknameEqualTo(String value) {
            addCriterion("u_nickname =", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameNotEqualTo(String value) {
            addCriterion("u_nickname <>", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameGreaterThan(String value) {
            addCriterion("u_nickname >", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("u_nickname >=", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameLessThan(String value) {
            addCriterion("u_nickname <", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameLessThanOrEqualTo(String value) {
            addCriterion("u_nickname <=", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameLike(String value) {
            addCriterion("u_nickname like", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameNotLike(String value) {
            addCriterion("u_nickname not like", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameIn(List<String> values) {
            addCriterion("u_nickname in", values, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameNotIn(List<String> values) {
            addCriterion("u_nickname not in", values, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameBetween(String value1, String value2) {
            addCriterion("u_nickname between", value1, value2, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameNotBetween(String value1, String value2) {
            addCriterion("u_nickname not between", value1, value2, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUPasswordIsNull() {
            addCriterion("u_password is null");
            return (Criteria) this;
        }

        public Criteria andUPasswordIsNotNull() {
            addCriterion("u_password is not null");
            return (Criteria) this;
        }

        public Criteria andUPasswordEqualTo(String value) {
            addCriterion("u_password =", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordNotEqualTo(String value) {
            addCriterion("u_password <>", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordGreaterThan(String value) {
            addCriterion("u_password >", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("u_password >=", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordLessThan(String value) {
            addCriterion("u_password <", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordLessThanOrEqualTo(String value) {
            addCriterion("u_password <=", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordLike(String value) {
            addCriterion("u_password like", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordNotLike(String value) {
            addCriterion("u_password not like", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordIn(List<String> values) {
            addCriterion("u_password in", values, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordNotIn(List<String> values) {
            addCriterion("u_password not in", values, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordBetween(String value1, String value2) {
            addCriterion("u_password between", value1, value2, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordNotBetween(String value1, String value2) {
            addCriterion("u_password not between", value1, value2, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUSexIsNull() {
            addCriterion("u_sex is null");
            return (Criteria) this;
        }

        public Criteria andUSexIsNotNull() {
            addCriterion("u_sex is not null");
            return (Criteria) this;
        }

        public Criteria andUSexEqualTo(Boolean value) {
            addCriterion("u_sex =", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexNotEqualTo(Boolean value) {
            addCriterion("u_sex <>", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexGreaterThan(Boolean value) {
            addCriterion("u_sex >", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexGreaterThanOrEqualTo(Boolean value) {
            addCriterion("u_sex >=", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexLessThan(Boolean value) {
            addCriterion("u_sex <", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexLessThanOrEqualTo(Boolean value) {
            addCriterion("u_sex <=", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexIn(List<Boolean> values) {
            addCriterion("u_sex in", values, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexNotIn(List<Boolean> values) {
            addCriterion("u_sex not in", values, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexBetween(Boolean value1, Boolean value2) {
            addCriterion("u_sex between", value1, value2, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexNotBetween(Boolean value1, Boolean value2) {
            addCriterion("u_sex not between", value1, value2, "uSex");
            return (Criteria) this;
        }

        public Criteria andUBindtelIsNull() {
            addCriterion("u_bindtel is null");
            return (Criteria) this;
        }

        public Criteria andUBindtelIsNotNull() {
            addCriterion("u_bindtel is not null");
            return (Criteria) this;
        }

        public Criteria andUBindtelEqualTo(String value) {
            addCriterion("u_bindtel =", value, "uBindtel");
            return (Criteria) this;
        }

        public Criteria andUBindtelNotEqualTo(String value) {
            addCriterion("u_bindtel <>", value, "uBindtel");
            return (Criteria) this;
        }

        public Criteria andUBindtelGreaterThan(String value) {
            addCriterion("u_bindtel >", value, "uBindtel");
            return (Criteria) this;
        }

        public Criteria andUBindtelGreaterThanOrEqualTo(String value) {
            addCriterion("u_bindtel >=", value, "uBindtel");
            return (Criteria) this;
        }

        public Criteria andUBindtelLessThan(String value) {
            addCriterion("u_bindtel <", value, "uBindtel");
            return (Criteria) this;
        }

        public Criteria andUBindtelLessThanOrEqualTo(String value) {
            addCriterion("u_bindtel <=", value, "uBindtel");
            return (Criteria) this;
        }

        public Criteria andUBindtelLike(String value) {
            addCriterion("u_bindtel like", value, "uBindtel");
            return (Criteria) this;
        }

        public Criteria andUBindtelNotLike(String value) {
            addCriterion("u_bindtel not like", value, "uBindtel");
            return (Criteria) this;
        }

        public Criteria andUBindtelIn(List<String> values) {
            addCriterion("u_bindtel in", values, "uBindtel");
            return (Criteria) this;
        }

        public Criteria andUBindtelNotIn(List<String> values) {
            addCriterion("u_bindtel not in", values, "uBindtel");
            return (Criteria) this;
        }

        public Criteria andUBindtelBetween(String value1, String value2) {
            addCriterion("u_bindtel between", value1, value2, "uBindtel");
            return (Criteria) this;
        }

        public Criteria andUBindtelNotBetween(String value1, String value2) {
            addCriterion("u_bindtel not between", value1, value2, "uBindtel");
            return (Criteria) this;
        }

        public Criteria andUEmailIsNull() {
            addCriterion("u_email is null");
            return (Criteria) this;
        }

        public Criteria andUEmailIsNotNull() {
            addCriterion("u_email is not null");
            return (Criteria) this;
        }

        public Criteria andUEmailEqualTo(String value) {
            addCriterion("u_email =", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailNotEqualTo(String value) {
            addCriterion("u_email <>", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailGreaterThan(String value) {
            addCriterion("u_email >", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailGreaterThanOrEqualTo(String value) {
            addCriterion("u_email >=", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailLessThan(String value) {
            addCriterion("u_email <", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailLessThanOrEqualTo(String value) {
            addCriterion("u_email <=", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailLike(String value) {
            addCriterion("u_email like", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailNotLike(String value) {
            addCriterion("u_email not like", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailIn(List<String> values) {
            addCriterion("u_email in", values, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailNotIn(List<String> values) {
            addCriterion("u_email not in", values, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailBetween(String value1, String value2) {
            addCriterion("u_email between", value1, value2, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailNotBetween(String value1, String value2) {
            addCriterion("u_email not between", value1, value2, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUHeadimgIsNull() {
            addCriterion("u_headimg is null");
            return (Criteria) this;
        }

        public Criteria andUHeadimgIsNotNull() {
            addCriterion("u_headimg is not null");
            return (Criteria) this;
        }

        public Criteria andUHeadimgEqualTo(String value) {
            addCriterion("u_headimg =", value, "uHeadimg");
            return (Criteria) this;
        }

        public Criteria andUHeadimgNotEqualTo(String value) {
            addCriterion("u_headimg <>", value, "uHeadimg");
            return (Criteria) this;
        }

        public Criteria andUHeadimgGreaterThan(String value) {
            addCriterion("u_headimg >", value, "uHeadimg");
            return (Criteria) this;
        }

        public Criteria andUHeadimgGreaterThanOrEqualTo(String value) {
            addCriterion("u_headimg >=", value, "uHeadimg");
            return (Criteria) this;
        }

        public Criteria andUHeadimgLessThan(String value) {
            addCriterion("u_headimg <", value, "uHeadimg");
            return (Criteria) this;
        }

        public Criteria andUHeadimgLessThanOrEqualTo(String value) {
            addCriterion("u_headimg <=", value, "uHeadimg");
            return (Criteria) this;
        }

        public Criteria andUHeadimgLike(String value) {
            addCriterion("u_headimg like", value, "uHeadimg");
            return (Criteria) this;
        }

        public Criteria andUHeadimgNotLike(String value) {
            addCriterion("u_headimg not like", value, "uHeadimg");
            return (Criteria) this;
        }

        public Criteria andUHeadimgIn(List<String> values) {
            addCriterion("u_headimg in", values, "uHeadimg");
            return (Criteria) this;
        }

        public Criteria andUHeadimgNotIn(List<String> values) {
            addCriterion("u_headimg not in", values, "uHeadimg");
            return (Criteria) this;
        }

        public Criteria andUHeadimgBetween(String value1, String value2) {
            addCriterion("u_headimg between", value1, value2, "uHeadimg");
            return (Criteria) this;
        }

        public Criteria andUHeadimgNotBetween(String value1, String value2) {
            addCriterion("u_headimg not between", value1, value2, "uHeadimg");
            return (Criteria) this;
        }

        public Criteria andUStateIsNull() {
            addCriterion("u_state is null");
            return (Criteria) this;
        }

        public Criteria andUStateIsNotNull() {
            addCriterion("u_state is not null");
            return (Criteria) this;
        }

        public Criteria andUStateEqualTo(Boolean value) {
            addCriterion("u_state =", value, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateNotEqualTo(Boolean value) {
            addCriterion("u_state <>", value, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateGreaterThan(Boolean value) {
            addCriterion("u_state >", value, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("u_state >=", value, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateLessThan(Boolean value) {
            addCriterion("u_state <", value, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateLessThanOrEqualTo(Boolean value) {
            addCriterion("u_state <=", value, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateIn(List<Boolean> values) {
            addCriterion("u_state in", values, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateNotIn(List<Boolean> values) {
            addCriterion("u_state not in", values, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateBetween(Boolean value1, Boolean value2) {
            addCriterion("u_state between", value1, value2, "uState");
            return (Criteria) this;
        }

        public Criteria andUStateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("u_state not between", value1, value2, "uState");
            return (Criteria) this;
        }

        public Criteria andUCreatetimeIsNull() {
            addCriterion("u_createtime is null");
            return (Criteria) this;
        }

        public Criteria andUCreatetimeIsNotNull() {
            addCriterion("u_createtime is not null");
            return (Criteria) this;
        }

        public Criteria andUCreatetimeEqualTo(Date value) {
            addCriterion("u_createtime =", value, "uCreatetime");
            return (Criteria) this;
        }

        public Criteria andUCreatetimeNotEqualTo(Date value) {
            addCriterion("u_createtime <>", value, "uCreatetime");
            return (Criteria) this;
        }

        public Criteria andUCreatetimeGreaterThan(Date value) {
            addCriterion("u_createtime >", value, "uCreatetime");
            return (Criteria) this;
        }

        public Criteria andUCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("u_createtime >=", value, "uCreatetime");
            return (Criteria) this;
        }

        public Criteria andUCreatetimeLessThan(Date value) {
            addCriterion("u_createtime <", value, "uCreatetime");
            return (Criteria) this;
        }

        public Criteria andUCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("u_createtime <=", value, "uCreatetime");
            return (Criteria) this;
        }

        public Criteria andUCreatetimeIn(List<Date> values) {
            addCriterion("u_createtime in", values, "uCreatetime");
            return (Criteria) this;
        }

        public Criteria andUCreatetimeNotIn(List<Date> values) {
            addCriterion("u_createtime not in", values, "uCreatetime");
            return (Criteria) this;
        }

        public Criteria andUCreatetimeBetween(Date value1, Date value2) {
            addCriterion("u_createtime between", value1, value2, "uCreatetime");
            return (Criteria) this;
        }

        public Criteria andUCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("u_createtime not between", value1, value2, "uCreatetime");
            return (Criteria) this;
        }

        public Criteria andUBirthdayIsNull() {
            addCriterion("u_birthday is null");
            return (Criteria) this;
        }

        public Criteria andUBirthdayIsNotNull() {
            addCriterion("u_birthday is not null");
            return (Criteria) this;
        }

        public Criteria andUBirthdayEqualTo(Date value) {
            addCriterion("u_birthday =", value, "uBirthday");
            return (Criteria) this;
        }

        public Criteria andUBirthdayNotEqualTo(Date value) {
            addCriterion("u_birthday <>", value, "uBirthday");
            return (Criteria) this;
        }

        public Criteria andUBirthdayGreaterThan(Date value) {
            addCriterion("u_birthday >", value, "uBirthday");
            return (Criteria) this;
        }

        public Criteria andUBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("u_birthday >=", value, "uBirthday");
            return (Criteria) this;
        }

        public Criteria andUBirthdayLessThan(Date value) {
            addCriterion("u_birthday <", value, "uBirthday");
            return (Criteria) this;
        }

        public Criteria andUBirthdayLessThanOrEqualTo(Date value) {
            addCriterion("u_birthday <=", value, "uBirthday");
            return (Criteria) this;
        }

        public Criteria andUBirthdayIn(List<Date> values) {
            addCriterion("u_birthday in", values, "uBirthday");
            return (Criteria) this;
        }

        public Criteria andUBirthdayNotIn(List<Date> values) {
            addCriterion("u_birthday not in", values, "uBirthday");
            return (Criteria) this;
        }

        public Criteria andUBirthdayBetween(Date value1, Date value2) {
            addCriterion("u_birthday between", value1, value2, "uBirthday");
            return (Criteria) this;
        }

        public Criteria andUBirthdayNotBetween(Date value1, Date value2) {
            addCriterion("u_birthday not between", value1, value2, "uBirthday");
            return (Criteria) this;
        }

        public Criteria andURemarkIsNull() {
            addCriterion("u_remark is null");
            return (Criteria) this;
        }

        public Criteria andURemarkIsNotNull() {
            addCriterion("u_remark is not null");
            return (Criteria) this;
        }

        public Criteria andURemarkEqualTo(String value) {
            addCriterion("u_remark =", value, "uRemark");
            return (Criteria) this;
        }

        public Criteria andURemarkNotEqualTo(String value) {
            addCriterion("u_remark <>", value, "uRemark");
            return (Criteria) this;
        }

        public Criteria andURemarkGreaterThan(String value) {
            addCriterion("u_remark >", value, "uRemark");
            return (Criteria) this;
        }

        public Criteria andURemarkGreaterThanOrEqualTo(String value) {
            addCriterion("u_remark >=", value, "uRemark");
            return (Criteria) this;
        }

        public Criteria andURemarkLessThan(String value) {
            addCriterion("u_remark <", value, "uRemark");
            return (Criteria) this;
        }

        public Criteria andURemarkLessThanOrEqualTo(String value) {
            addCriterion("u_remark <=", value, "uRemark");
            return (Criteria) this;
        }

        public Criteria andURemarkLike(String value) {
            addCriterion("u_remark like", value, "uRemark");
            return (Criteria) this;
        }

        public Criteria andURemarkNotLike(String value) {
            addCriterion("u_remark not like", value, "uRemark");
            return (Criteria) this;
        }

        public Criteria andURemarkIn(List<String> values) {
            addCriterion("u_remark in", values, "uRemark");
            return (Criteria) this;
        }

        public Criteria andURemarkNotIn(List<String> values) {
            addCriterion("u_remark not in", values, "uRemark");
            return (Criteria) this;
        }

        public Criteria andURemarkBetween(String value1, String value2) {
            addCriterion("u_remark between", value1, value2, "uRemark");
            return (Criteria) this;
        }

        public Criteria andURemarkNotBetween(String value1, String value2) {
            addCriterion("u_remark not between", value1, value2, "uRemark");
            return (Criteria) this;
        }

        public Criteria andUUpdateIsNull() {
            addCriterion("u_update is null");
            return (Criteria) this;
        }

        public Criteria andUUpdateIsNotNull() {
            addCriterion("u_update is not null");
            return (Criteria) this;
        }

        public Criteria andUUpdateEqualTo(Date value) {
            addCriterion("u_update =", value, "uUpdate");
            return (Criteria) this;
        }

        public Criteria andUUpdateNotEqualTo(Date value) {
            addCriterion("u_update <>", value, "uUpdate");
            return (Criteria) this;
        }

        public Criteria andUUpdateGreaterThan(Date value) {
            addCriterion("u_update >", value, "uUpdate");
            return (Criteria) this;
        }

        public Criteria andUUpdateGreaterThanOrEqualTo(Date value) {
            addCriterion("u_update >=", value, "uUpdate");
            return (Criteria) this;
        }

        public Criteria andUUpdateLessThan(Date value) {
            addCriterion("u_update <", value, "uUpdate");
            return (Criteria) this;
        }

        public Criteria andUUpdateLessThanOrEqualTo(Date value) {
            addCriterion("u_update <=", value, "uUpdate");
            return (Criteria) this;
        }

        public Criteria andUUpdateIn(List<Date> values) {
            addCriterion("u_update in", values, "uUpdate");
            return (Criteria) this;
        }

        public Criteria andUUpdateNotIn(List<Date> values) {
            addCriterion("u_update not in", values, "uUpdate");
            return (Criteria) this;
        }

        public Criteria andUUpdateBetween(Date value1, Date value2) {
            addCriterion("u_update between", value1, value2, "uUpdate");
            return (Criteria) this;
        }

        public Criteria andUUpdateNotBetween(Date value1, Date value2) {
            addCriterion("u_update not between", value1, value2, "uUpdate");
            return (Criteria) this;
        }

        public Criteria andUProvinceidIsNull() {
            addCriterion("u_provinceid is null");
            return (Criteria) this;
        }

        public Criteria andUProvinceidIsNotNull() {
            addCriterion("u_provinceid is not null");
            return (Criteria) this;
        }

        public Criteria andUProvinceidEqualTo(Integer value) {
            addCriterion("u_provinceid =", value, "uProvinceid");
            return (Criteria) this;
        }

        public Criteria andUProvinceidNotEqualTo(Integer value) {
            addCriterion("u_provinceid <>", value, "uProvinceid");
            return (Criteria) this;
        }

        public Criteria andUProvinceidGreaterThan(Integer value) {
            addCriterion("u_provinceid >", value, "uProvinceid");
            return (Criteria) this;
        }

        public Criteria andUProvinceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("u_provinceid >=", value, "uProvinceid");
            return (Criteria) this;
        }

        public Criteria andUProvinceidLessThan(Integer value) {
            addCriterion("u_provinceid <", value, "uProvinceid");
            return (Criteria) this;
        }

        public Criteria andUProvinceidLessThanOrEqualTo(Integer value) {
            addCriterion("u_provinceid <=", value, "uProvinceid");
            return (Criteria) this;
        }

        public Criteria andUProvinceidIn(List<Integer> values) {
            addCriterion("u_provinceid in", values, "uProvinceid");
            return (Criteria) this;
        }

        public Criteria andUProvinceidNotIn(List<Integer> values) {
            addCriterion("u_provinceid not in", values, "uProvinceid");
            return (Criteria) this;
        }

        public Criteria andUProvinceidBetween(Integer value1, Integer value2) {
            addCriterion("u_provinceid between", value1, value2, "uProvinceid");
            return (Criteria) this;
        }

        public Criteria andUProvinceidNotBetween(Integer value1, Integer value2) {
            addCriterion("u_provinceid not between", value1, value2, "uProvinceid");
            return (Criteria) this;
        }

        public Criteria andUCityidIsNull() {
            addCriterion("u_cityid is null");
            return (Criteria) this;
        }

        public Criteria andUCityidIsNotNull() {
            addCriterion("u_cityid is not null");
            return (Criteria) this;
        }

        public Criteria andUCityidEqualTo(Integer value) {
            addCriterion("u_cityid =", value, "uCityid");
            return (Criteria) this;
        }

        public Criteria andUCityidNotEqualTo(Integer value) {
            addCriterion("u_cityid <>", value, "uCityid");
            return (Criteria) this;
        }

        public Criteria andUCityidGreaterThan(Integer value) {
            addCriterion("u_cityid >", value, "uCityid");
            return (Criteria) this;
        }

        public Criteria andUCityidGreaterThanOrEqualTo(Integer value) {
            addCriterion("u_cityid >=", value, "uCityid");
            return (Criteria) this;
        }

        public Criteria andUCityidLessThan(Integer value) {
            addCriterion("u_cityid <", value, "uCityid");
            return (Criteria) this;
        }

        public Criteria andUCityidLessThanOrEqualTo(Integer value) {
            addCriterion("u_cityid <=", value, "uCityid");
            return (Criteria) this;
        }

        public Criteria andUCityidIn(List<Integer> values) {
            addCriterion("u_cityid in", values, "uCityid");
            return (Criteria) this;
        }

        public Criteria andUCityidNotIn(List<Integer> values) {
            addCriterion("u_cityid not in", values, "uCityid");
            return (Criteria) this;
        }

        public Criteria andUCityidBetween(Integer value1, Integer value2) {
            addCriterion("u_cityid between", value1, value2, "uCityid");
            return (Criteria) this;
        }

        public Criteria andUCityidNotBetween(Integer value1, Integer value2) {
            addCriterion("u_cityid not between", value1, value2, "uCityid");
            return (Criteria) this;
        }

        public Criteria andUAreaidIsNull() {
            addCriterion("u_areaid is null");
            return (Criteria) this;
        }

        public Criteria andUAreaidIsNotNull() {
            addCriterion("u_areaid is not null");
            return (Criteria) this;
        }

        public Criteria andUAreaidEqualTo(Integer value) {
            addCriterion("u_areaid =", value, "uAreaid");
            return (Criteria) this;
        }

        public Criteria andUAreaidNotEqualTo(Integer value) {
            addCriterion("u_areaid <>", value, "uAreaid");
            return (Criteria) this;
        }

        public Criteria andUAreaidGreaterThan(Integer value) {
            addCriterion("u_areaid >", value, "uAreaid");
            return (Criteria) this;
        }

        public Criteria andUAreaidGreaterThanOrEqualTo(Integer value) {
            addCriterion("u_areaid >=", value, "uAreaid");
            return (Criteria) this;
        }

        public Criteria andUAreaidLessThan(Integer value) {
            addCriterion("u_areaid <", value, "uAreaid");
            return (Criteria) this;
        }

        public Criteria andUAreaidLessThanOrEqualTo(Integer value) {
            addCriterion("u_areaid <=", value, "uAreaid");
            return (Criteria) this;
        }

        public Criteria andUAreaidIn(List<Integer> values) {
            addCriterion("u_areaid in", values, "uAreaid");
            return (Criteria) this;
        }

        public Criteria andUAreaidNotIn(List<Integer> values) {
            addCriterion("u_areaid not in", values, "uAreaid");
            return (Criteria) this;
        }

        public Criteria andUAreaidBetween(Integer value1, Integer value2) {
            addCriterion("u_areaid between", value1, value2, "uAreaid");
            return (Criteria) this;
        }

        public Criteria andUAreaidNotBetween(Integer value1, Integer value2) {
            addCriterion("u_areaid not between", value1, value2, "uAreaid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 13 14:55:36 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbggenerated Mon Nov 13 14:55:36 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}